---
title: "rawR - Technical Note, Journal of Proteome Research, Second Biennial Special Issue on Software Tools and Resources in February 2021"
author: "Tobias Kockmann / Christian Panse"
date: "8/27/2020"
output: pdf_document
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{rawR JPR Technical Note}
  %\usepackage[utf8]{inputenc}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

The Bioconductor project has shown that the R statistical environment is a highly valuable tool for genomics data analysis (https://www.nature.com/articles/nmeth.3252), but with respect to proteomics we are still missing low level infrastructure to enable performant and robust analysis workflows in R. Fundamentally important are libraries that provide raw data access. Our R package rawDiag (doi:10.1021/acs.jproteome.8b00173) has provided the proof-of-principle how access to mass spectromerty raw files can be realized by wrapping vendor-provided APIs. Our novel package rawR now aims for complete, OS independent access to all spectral, chromatographic and meta data logged in Thermo Fisher Scientific raw files. rawR interoperates with other R packages for proteomics data visualisation (protViz) and will ...

## Keywords

proteomics, software, R package

## Introduction

...


## Implementation

### C# code

### R

Mass spectrometry uses two basic building blocks (data items): 1. mass spectrum, 2. chromatogram. All mass spectra are recorded by scanning detectors (mass analyzers) that log signal intensities for ranges of mass to charge ratios (m/z), also referred to as position. These recordings can be of continuous nature so called profile data, or appear centroided in case discrete information (tuples of position and intensity values) is sufficient. This heavily compacted data structure is often called a peak list. In addition to signal intensities, peak list can also cover additional attributes like peak resolution, charge, or local noise around the peak. In short, the additional attributes further described the nature of the original profile signal, or help to group peak lists with respect to their molecular nature. A well-known example is the assignment to peak groups that constitute isotope patterns (M, M+1, M+2, ...). Chromatograms come in different flavours, but are always signal intensity values as a function of time. Signal intensities can be point estimates from scanning detectors or plain intensities from non scaning detectors (e.g. UV trace). Point estimates can be defined in different ways by for instance summing all signals of a given spectrum (total ion chromatogram or TIC), or by extracting signal around an expected value (extracted ion chromatogram = XIC), or by using the maximum signal (base peak chromatogram = BPC). On top, chromatograms can be computed from prefiltered lists of scans. A TIC for instance is typically generated by iterating over all MS1 scans. 

We therefore decided to implemented objects in R that represent these basic building blocks in a simple, but effective manner.

### Example data

The binary example file sample.raw contains 574 fourier-transformed orbi trap spectra (FTMS) recorded on a Thermo Fisher Scientific Q Exactive HF-X. The mass spectrometer was operated in line with a nano electrospray source (NSI) in positive mode (+). All spectra were writen to disk after applying centroiding (c) and lock mass correction. Additional raw data for demonstration and extented testing is vaialable through the [tartare package](https://bioconductor.org/packages/tartare/). Lions love raw meat!

## Results

### Use Case I - Analyzing orbi trap spectra

...

### Use Case II - Working with chromatograms - iRT regression

...


## Conclusions

...


## Author information

...

### Corresponding author

...

### Author contributions

The manuscript was written through contributions of all authors. All authors have given approval to the final version of the manuscript. ‡These authors contributed equally. (match statement to author names with a symbol)


### Funding Sources
Any funds used to support the research of the manuscript should be placed here (per journal style).


## Acknowledgements

(Word Style “TD_Acknowledgments”). Generally the last paragraph of the paper is the place to acknowledge people, organizations, and financing (you may state grant numbers and sponsors here). Follow the journal’s guidelines on what to include in the Acknowledgments section.


## ABBREVIATIONS
CCR2, CC chemokine receptor 2; CCL2, CC chemokine ligand 2; CCR5, CC chemokine receptor 5; TLC, thin layer chromatography.


## References



