# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-CMD-check-rawrr
env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        r-version: [4.5]
    steps:
      - uses: actions/checkout@v4
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install Linux packages
        run: sudo apt-get install -y libcurl4-openssl-dev libicu-dev pandoc texlive texlive-latex-extra texlive-fonts-extra
        shell: bash {0}
      - name: Install dependencies
        run: |
          install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))
          pak::pkg_install(c("covr", "rcmdcheck", "rmarkdown", "protViz", "testthat", "knitr"))
          pak::pkg_install(c("bioc::BiocStyle", "bioc::ExperimentHub", "bioc::tartare"))
          pak::local_install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(build_args = "", args = "", error_on = "error", check_dir = "/tmp/rawrr.Rcheck")
        shell: Rscript {0}
      - name: codecov
        run: covr::codecov(type = "all",token=Sys.getenv('CODECOV_TOKEN'))
        shell: Rscript {0}
      - uses: actions/upload-artifact@v4
        with:
            name: rawrr.Rcheck
            path: /tmp/rawrr.Rcheck
            if-no-files-found: warn
